export const post = {
	title: "Excavateur Cat",
	category: "Vehicles",
	subCategory: "Utilities",
	postType: "offer",
	options: {
		brand: "MERCEDES-BENZ",
		model: "",
		modelYear: "1999",
		fuel: "Diesel",
		price: "20000",
		discription: "une excavatrice ancienne mais fiable",
		address: "Toulouse (31000)",
		reference: "11/0023",
		gearbox: "Automatic",
		numberOfDoors: "4",
		numberOfPlaces: "2",
		color: "White",
		air: "3",
		spareParts: "Not available",
		plateNumber: "AF-125-AN",
		taxPower: "",
		dinPower: "",
		mileage: "1750000",
	},
	images: [],
}