import "./globals.css";
import ContextProvider from "@/context/ContextProviedr";
import  { Toaster } from 'react-hot-toast';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
// import { ClerkProvider } from "@clerk/nextjs";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 <ClerkProvider>
    <html lang="en">
      <body
      >
           {/* <header>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
               
              </header> */}
        <ContextProvider>
        {children}
        <Toaster />
        </ContextProvider>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
