import "./globals.css";
import ContextProvider from "@/context/ContextProviedr";
// import { ClerkProvider } from "@clerk/nextjs";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
    <html lang="en">
      <body
      >
        <ContextProvider>
        {children}
        </ContextProvider>
       
      </body>
    </html>
  
  );
}
