export const post = {
	title: "marmite",
	category: "Home & Garden",
	subCategory: "Household appliances",
	postType: "offer",
	options: {
		kind: "Kitchen",
		product: "Cooking appliance",
		brand: "Beaba",
		state: "New condition",
		newItemType: "Liquidation de stock",
		RefurbishedCondition: "",
		spareParts: "Not available",
		generalConditionsOfSale: "",
		description: "marmite en acier inoxydable",
		address: "Le Mans (72000)",
		sellingPrice: "40",
		newPrice: "",
		reference: "652",
		quantity: "1",
		packageWeight: "Up to 100g",
		newProductType: "Clearance",
		refurbishedItemType: "Good condition",
	},
	images: []
};
